stockNumber: 5
# How Many Stocks Show People in Once

stockName:
  - "재강전자"
  - "주호산업"
  - "인우기술"
  - "지민조선"
  - "창운소프트웨어"
  - "서윤로봇"
  - "다민방산"
  - "종서운수"
  - "채원엔터테인먼트"
  - "짱후무역"
# Write Your Stocks' Name

defaultStockPrice: 20
# Default Stock Price

stockUpdateTime: 60
# Stock Update Time (s)


maxStockDelta: 50
# Max Stock Delta

stockUpMessage:
  - "신기술 개발 성공!"
  - "화성 착륙 성공!"
  - "국책 연구 사업 수주 성공!"
  - "미국과 기술 협약 성공!"
  - "중국과 수억대 계약 성공!"
# Write Your Stock Up Message

stockDownMessage:
    - "사장의 비리 정황 파악"
    - "관련주 하락"
    - "탈세 혐의 파악"
    - "미국에게 무역 재재 가동"
    - "로켓 발사 실패"
# Write Your Stock Down Message

stockFailMessage:
  - "상장 폐지!"
  - "파산!"
# Write Your Stock Fail Message

stockSuccessMessage:
  - "상장 성공!"
  - "주식 시장에 호기로운 도전!"
# Write Your Stock Success Message

defaultMoney: 0
# Default Money

defaultOre:
  Iron: 1
  Gold: 10
  Emerald: 50
  Diamond: 100
  Netherite: 500
# Default Resource

oreUpdateTime: 60
# Ore Update Time (s)

maxEnchantLevel: 5
# Max Enchant Level

maxEnchantAmount: 3
# Max Enchant Amount